services:
  front-end:
    build: ./front-end
    ports:
      - 3001:80
    environment:
      API_BASE_URL: "http://localhost:3000"
  back-end:
    build: ./back-end
    ports:
      - 3000
    deploy:
      replicas: 2
  load-balancer:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - back-end
